from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    action: str  # "BUY" or "SELL"
    pair: str
    price: float
    strategy: str  # Strategy name that generated this
    timeframe: str
    confidence: int  # 1-5 (1=weak, 5=very strong)
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reasons: list[str] = field(default_factory=list)
    indicators: dict = field(default_factory=dict)
    learning_points: list[str] = field(default_factory=list)

    @property
    def risk_reward_ratio(self) -> Optional[float]:
        if self.stop_loss and self.take_profit:
            risk = abs(self.price - self.stop_loss)
            reward = abs(self.take_profit - self.price)
            if risk > 0:
                return round(reward / risk, 2)
        return None


class BaseStrategy:
    """Base class for all trading strategies."""

    name: str = "base"
    description: str = ""

    async def analyze(self, df, indicators: dict, pair: str, timeframe: str) -> Optional[Signal]:
        """Analyze market data and return a Signal if conditions are met."""
        raise NotImplementedError
